In [4]:
#pip install plotly
#pip install -U kaleido
#pip install -U nbformat
#pip install statsmodels

In [6]:
# definindo as configurações

# autoreload permite a recarga dos módulos antes da execução dos códigos
# doc: https://ipython.org/ipython-doc/3/config/extensions/autoreload.html
%reload_ext autoreload
%autoreload 2

### Atividade

Resolver as questões abaixo. Em seguida, criar um repositório público no GitHub e armazenar no notebook criado, enviando somente o link do NOTEBOOK para o [Formulário](https://docs.google.com/forms/d/e/1FAIpQLSf8IUCLt4kowhHhB3SRQofE2I8NuXuDadBYjRHqUxgb3yWOaQ/viewform).

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px


#### Questão 1

Criar 2 vetores, um com uma série historica de anos de 1970 até 2022 e um segundo vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 1 a 20000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

In [8]:
#eixo x com tempo e eixo y com valor de 1 a 20000 - gráfico de linhas
anos = np.arange(1970, 2023)
anos

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [9]:
valores = np.random.randint(1, 200001, len(anos))
valores

array([186621,  77934,  34962,  87465,  43250,  82335, 136244, 179771,
        71817, 188454,  23203, 143773,  98559, 194390, 192576,  82398,
       119603,  88330, 198557, 108018,  41490,  59870, 110559, 193305,
        13172, 182695, 183919, 171562, 116373, 146116, 166546, 113294,
          277,  14187,  74115, 136763, 151195, 128192, 150845,   9649,
       126598, 148273, 116842, 159069,  72751,  94627,  40680, 132126,
        55719, 176110,  55256,  79985, 103132])

In [12]:
px.line(x=anos, y=valores)

#### Questão 2

Criar uma lista com as letras do alfabeto, depois um vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 10 a 100. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

Utilize o objeto string para resolver a questão:

```
import string
string.ascii_lowercase
```

In [13]:
import string as str

In [19]:
letters = list(str.ascii_lowercase)
letters

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [20]:
num = np.random.randint(10, 101, len(letters))
num

array([43, 73, 10, 90, 54, 62, 61, 84, 67, 46, 34, 22, 50, 38, 91, 44, 49,
       90, 19, 70, 28, 78, 68, 98, 18, 84])

In [24]:
px.bar(x=letters, y=num, text=num, color=letters)

#### Questão 3

Criar 2 vetores com a mesma quantidade de observações, 500 registros , de números inteiros aleatórios, o primeiro variando de 1000 a 2000, o segundo variando de 5000 a 10000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express, demonstrando relação entre as variáveis.

In [25]:
arr1 = np.random.randint(1000,2001,500)
arr2 = np.random.randint(5000,100001,500)

In [28]:
px.scatter(x=arr1, y=arr2)
#trendline='ols' statsmodel

#### Questão 4

Criar uma vetor com 500 registros de números inteiros variando entre 125 e 857. Em seguida montar um gráfico que mostre a dispersão com a melhor visualização para os dados com a biblioteca Plotly Express.

In [30]:
arr1 = np.random.randint(125, 858, 500)

In [36]:
px.box(y=arr1)

In [33]:
px.histogram(x=arr1)